### ISSUE TITLE
Gulp build is not working with below error

### ISSUE THREAD

**Issue by nkhs** [vaalentin/2015#8]
```
gulp build
ReferenceError: primordials is not defined
    at fs.js:45:5
    at req_ (C:\Users\Admin\Desktop\2015\node_modules\natives\index.js:143:24)
    at Object.req [as require] (C:\Users\Admin\Desktop\2015\node_modules\natives\index.js:55:10)
    at Object.<anonymous> (C:\Users\Admin\Desktop\2015\node_modules\vinyl-fs\node_modules\graceful-fs\fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
```

**Comment by nkhs** [comment]
I installed node.js version 10, and working

**Comment by DamiTesfaye** [comment]
If you are using npm
Run this command to know which version of npm you are using:

`npm -v`

It will return a version number <major>.<minor>.<patch> such as 8.4.0.

If your version is v8.3.0 or above, then you can override the version of graceful-fs by adding [an overrides section](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) in your package.json file:

```
{
  "overrides": {
    "graceful-fs": "^4.2.11"
  }
}
```

Otherwise, you need to use [npm-force-resolutions](https://github.com/rogeriochaves/npm-force-resolutions) as a preinstall script to be able to override the version of graceful-fs by changing your package.json file like this:

```
{
  "scripts": {
    "preinstall": "npx npm-force-resolutions"
  },
  "resolutions": {
    "graceful-fs": "^4.2.11"
  }
}
```

npm-force-resolutions will alter the package-lock.json file to set graceful-fsto the wanted version before the install is done.

If you are using a custom .npmrc file in your project and it contains either a proxy or custom registry, you might need to change npx npm-force-resolutions to npx --userconfig .npmrc npm-force-resolutions because some versions of npx don't use the current folder .npmrc file by default.
